version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - postgresql
      - app
    env_file:
      - .env

volumes:
  postgres_data:
