# Generated by Django 5.1.2 on 2024-10-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_categories',
            field=models.CharField(max_length=50, null=True, verbose_name='Дочерняя категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nm_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Артикул товара'),
        ),
    ]
